language: cpp
sudo: false

linux64_addons:
    addons: &linux64
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-4.8
        - doxygen
        - valgrind
        # Used for CHFL_EXTERNAL_NETCDF
        - libnetcdf-dev

linux32_addons:
    addons: &linux32
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-4.8
        - doxygen
        - valgrind
        - g++-4.8-multilib
        - linux-libc-dev:i386
        - libc6-dev-i386

matrix:
  fast_finish: true
  include:
    - os: linux
      env: SHARED_LIBS=OFF EMSCRIPTEN=ON
      addons:
        apt:
          packages:
          - doxygen
    - os: linux
      compiler: clang
      env: SHARED_LIBS=ON CMAKE_EXTRA=-DCHFL_SYSTEM_NETCDF=ON
      addons: *linux64
    - os: linux
      compiler: clang
      env: SHARED_LIBS=OFF DEPLOY_DOCS=ON
      addons: *linux64
    - os: linux
      compiler: gcc
      env: SHARED_LIBS=ON
      addons: *linux64
    - os: linux
      compiler: gcc
      env: SHARED_LIBS=OFF
      addons: *linux64
    - os: linux
      compiler: gcc
      env: SHARED_LIBS=ON ARCH="x86" CMAKE_EXTRA=-DHAVE_LIBM=/lib32/libm.so.6
      addons: *linux32
    - os: linux
      compiler: gcc
      env: SHARED_LIBS=OFF ARCH="x86" CMAKE_EXTRA=-DHAVE_LIBM=/lib32/libm.so.6
      addons: *linux32
    - os: osx
      compiler: clang
      env: SHARED_LIBS=ON
    - os: osx
      compiler: clang
      env: SHARED_LIBS=OFF
    - os: osx
      compiler: gcc
      env: SHARED_LIBS=ON
    - os: osx
      compiler: gcc
      env: SHARED_LIBS=OFF

before_install:
  # Setting environement
  - cd $TRAVIS_BUILD_DIR
  - source scripts/ci/setup-travis.sh
  - $CC --version
  - $CXX --version

script:
  - cd $TRAVIS_BUILD_DIR
  - mkdir build && cd build
  - $CMAKE_CONFIGURE cmake $CMAKE_ARGS $CMAKE_EXTRA ..
  - make -j2
  - ctest -j2 --output-on-failure
  - ccache -s
  - cd $TRAVIS_BUILD_DIR
  # Check C API documentation
  - ./scripts/ci/check-capi.py
  # Build docs
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        ./scripts/ci/build-docs.sh
    fi
  # Generate and upload coverage
  - |
    if ${DO_COVERAGE_ON_TRAVIS}; then
        cd $TRAVIS_BUILD_DIR
        find . -type f -name '*.gcno' -exec gcov-4.8 -pb {} +
        rm -f \#usr\#*.gcov
        rm -f *\#external\#*.gcov
        codecov -X gcov
    fi

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: build/gh-pages
  on:
    branch: master
    tags: true
    condition: $DEPLOY_DOCS == ON

cache: ccache
