version: "{build}"

os:
  - Visual Studio 2015
  - MinGW

clone_depth: 10
clone_folder: c:\Chemharp

build:
  verbosity: minimal
matrix:
  fast_finish: true

notifications:
  - provider: Email
    to: [luthaf@luthaf.fr]
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true

install:
  - git submodule update --init --recursive

build_script:
  - cd C:\Chemharp
  - mkdir build
  - cd build
  - cmake -DBUILD_TESTS=ON ..
  - cmake --build . --config debug --target ALL_BUILD

test_script:
  - ctest --build-config debug --output-on-failure -E dcd-molfile
